name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write            # GITHUB_TOKEN 푸시 권한

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 소스 체크아웃
      - uses: actions/checkout@v4

      # 2) Node 설치
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3) .env.production 생성
      - name: Generate env file
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }}"       >> .env.production
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.production

      # 4) 의존성 설치 & 빌드
      - run: npm ci
      - run: npm run build -- --mode production   # Vite이면 이 스크립트가 package.json에 있어야 함

      # 5) gh-pages 브랜치 배포
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
