name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]          # 기본 브랜치 이름이 main이 아니면 수정

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 소스 체크아웃
      - uses: actions/checkout@v4

      # 2) Node 설치
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3) .env.production 파일 생성 (Secrets 주입)
      - name: Generate env file
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }}"       >> .env.production
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.production

      # 4) 의존성 설치 & 빌드
      - run: npm ci        # package-lock.json이 없다면 npm install
      - run: npm run build -- --mode production

      # 5) gh-pages 브랜치로 배포
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist         # Vite 기본 출력 디렉터리
